### ISSUE TITLE
formating .md files

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Ruby-for-Beginner#105]
there are many .md and some files are not in format,
please help me to reformat to those files
thank you :smile:

**Comment by MePsyDuck** [comment]
Can you provide a list of files which are not formatted properly and which ones are already taken/being worked on to avoid conflicts?

**Comment by MePsyDuck** [comment]
Also, any readme to use as reference?

**Comment by avsingh999** [comment]
@MePsyDuck  no, there is no reference. You can add your reference?
thanks :)

**Comment by MePsyDuck** [comment]
@avsingh999 No reference for me either, just formatting the way I like it as for now.
@enriquezm Yeah sure, go ahead. I'm doing them from bottom up. I'll cover all files following  	pull_request_template.md if no one else is working on them.
