### ISSUE TITLE
String Interpolation in ruby

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Ruby-for-Beginner#13]
#### create .md file name should be like title of issue

**Comment by mayanktap** [comment]
Hi @avsingh999 , I would like to work on this.

**Comment by avsingh999** [comment]
@mayanktap  go ahead

**Comment by mayanktap** [comment]
Can you please give me access rights to push the file?

**Comment by avsingh999** [comment]
@mayanktap
- fork this repository
- create a file in that repository 
- then create a pull request

##### you can refer these link
1. https://guides.github.com/activities/forking/
2. https://help.github.com/articles/creating-new-files/
3. https://services.github.com/on-demand/intro-to-github/create-pull-request

##### fell free to ask me  any type help
Thank you

**Comment by mayanktap** [comment]
https://github.com/avsingh999/Ruby-for-Beginner/pull/21

Please check.
