### ISSUE TITLE
how to use map in ruby?

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Ruby-for-Beginner#66]
### create .md file name should be like title of issue
❤️ thanks :) ❤️

**Comment by wilbertliu** [comment]
Hello @avsingh999 😀,

May I take this one? Would love to write something about `map` on Ruby.
Thanks a lot! 🙏🏻

**Comment by avsingh999** [comment]
@wilbertliu  great,
go ahead

**Comment by wilbertliu** [comment]
Sure! Thank you Avkaran! 🙏🏻

Sincerely,
Wilbert Liu
